import Link from 'next/link';
import { getResumenVacantes } from '@/lib/actions/proceso';
import { createClient } from '@/lib/supabase/server';
import type { Notificacion } from '@/lib/supabase/types';
import { NotificationCenter } from '@/components/proceso/notification-center';
import { Semaforo } from '@/components/proceso/semaforo';
import { NOMBRE_ETAPA } from '@/lib/orquestador/estados';
import { ChatAsistenteHM } from '@/components/ia/ChatAsistenteHM';

export default async function HmDashboard() {
  const [resumen, supabase] = await Promise.all([getResumenVacantes(), createClient()]);
  const { data: notificaciones } = await supabase.from('notificaciones').select('*').order('ts', { ascending: false }).limit(8);
  const vacantes = resumen.ok ? resumen.data : [];
  const pendientes = vacantes.filter((v) => v.estado.startsWith('ESPERANDO_HM_'));
  return <div className="space-y-8"><section><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#c8105a]">Hiring Manager</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Tu proceso, en una vista</h1><p className="mt-2 text-slate-600">Prioriza las decisiones que desbloquean a tu equipo.</p></section>{!resumen.ok && <p role="alert" className="rounded-lg bg-rose-50 p-4 text-rose-700">{resumen.codigo}: {resumen.error}</p>}<section><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-semibold">Requieren tu decisión</h2><span className="rounded-full bg-[#c8105a] px-2.5 py-1 text-sm font-bold text-white">{pendientes.length}</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{pendientes.length ? pendientes.map((v) => <Link key={v.id} href={`/hm/vacantes/${v.id}`} className="rounded-xl border border-[#c8105a]/30 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow"><p className="text-xs font-semibold uppercase tracking-wide text-[#c8105a]">{v.estado.replace('ESPERANDO_HM_', '').replaceAll('_', ' ')}</p><h3 className="mt-2 font-semibold">{v.titulo}</h3><p className="mt-3 text-sm text-slate-600">{v.responsable.nombre ?? 'HM'} tiene la decisión.</p><span className="mt-4 inline-block text-sm font-semibold text-[#c8105a]">Revisar candidatos →</span></Link>) : <p className="rounded-xl border border-dashed border-stone-300 p-5 text-sm text-slate-500">No tienes compuertas pendientes.</p>}</div></section><section><h2 className="mb-3 text-xl font-semibold">Vacantes a tu cargo</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{vacantes.map((v) => <Link key={v.id} href={`/hm/vacantes/${v.id}`} className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm transition hover:border-[#c8105a]"><div className="flex justify-between gap-3"><h3 className="font-semibold">{v.titulo}</h3><Semaforo color={v.color} /></div><p className="mt-3 text-sm text-slate-600">{NOMBRE_ETAPA[v.etapa_actual]} · {v.estado.replaceAll('_', ' ')}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-500">Días restantes</dt><dd className="font-semibold">{v.dias_restantes ?? '—'}</dd></div><div><dt className="text-slate-500">Cobertura estimada</dt><dd className="font-semibold">{v.fecha_estimada_cobertura ?? '—'}</dd></div></dl>{v.bloquea && <p className="mt-4 rounded-md bg-rose-50 p-2 text-xs text-rose-800">Bloquea: {v.bloquea.nombre ?? v.bloquea.rol}</p>}</Link>)}</div></section><section className="rounded-xl border border-[#c8105a]/30 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-[#c8105a]">Asistente del HM</p><h2 className="mt-1 text-lg font-semibold">¿Qué tengo que hacer hoy?</h2><p className="mt-2 text-sm text-slate-600">Tus pendientes reales, ordenados por prioridad: primero lo atrasado y lo que bloquea a otros.</p><ChatAsistenteHM /></section><NotificationCenter notificaciones={(notificaciones ?? []) as Notificacion[]} /></div>;
}
